name: Playwright Tests
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    if: github.event.deployment_status.state == 'success'
    container:
      image: mcr.microsoft.com/playwright:v1.41.0-jammy
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Playwright tests
        run: HOME='/root' pnpm run test --reporter=html --reporter=junit
        env:
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: playwright-results.xml
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results
          path: playwright-results.xml
          retention-days: 30
